name: specialico
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.4+5

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.4
  riverpod_annotation: ^2.0.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  cloud_firestore: ^4.5.0
  firebase_core_platform_interface: ^4.2.3
  cached_network_image: ^3.2.3
  metadata_fetch: ^0.4.1
  flutter_sticky_header: ^0.6.5
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.5
  expandable_page_view: ^1.0.17
  dots_indicator: ^2.1.0
  url_launcher: ^6.1.10
  zoom_pinch_overlay: ^1.4.1+3
  vector_math: ^2.1.4
  skeleton_loader: ^2.0.0+4
  geolocator: ^9.0.2
  firebase_core: ^2.15.0
  animated_flip_counter: ^0.2.5
  beamer: ^1.5.3
  rxdart: ^0.27.7
  geoflutterfire_plus: ^0.0.9
  google_maps_flutter: ^2.2.6
  google_maps_cluster_manager: ^3.0.0+1
  flutter_native_splash: ^2.2.19
  firebase_auth: ^4.7.1
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^5.0.0
  font_awesome_flutter: ^10.5.0
  flutter_custom_clippers: ^2.1.0
  email_validator: ^2.1.17
  charset_converter: ^2.1.1
  flutter_onboarding_slider: ^1.0.9
  image: ^4.0.17
  image_picker: ^1.0.1
  flutter_image_compress: ^2.0.4
  firebase_storage: ^11.2.5
  flutter_cache_manager: ^3.3.1
  google_mobile_ads: ^3.0.0
  flutter_dotenv: ^5.1.0
  modal_bottom_sheet: ^3.0.0-pre
  http: ^0.13.3
  direct_select_flutter: ^1.1.1
  firebase_crashlytics: ^3.3.4
  firebase_analytics: ^10.4.4
  shared_preferences: ^2.2.0
  app_tracking_transparency: ^2.0.4
  app_settings: ^5.0.0
  stack_trace:

  dismissible_page:
    git:
      url: https://github.com/KosukeOnishi/Flutter_dismissible_page

  preload_page_view: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  riverpod_generator: ^2.1.6
  riverpod_lint: ^1.2.0
  flutter_launcher_icons: "^0.13.1"
  flutter_oss_licenses: ^2.0.1
  test: ^1.24.0
  mockito: ^5.4.2
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/adaptive_background.png
    - assets/images/adaptive_foreground.png
    - assets/images/background.png
    - assets/images/beans_dark.png
    - assets/images/beans_light.png
    - assets/images/beans_medium.png
    - assets/images/fav.png
    - assets/images/favicon.png
    - assets/images/google_light.png
    - assets/images/Google_Maps_icon.svg
    - assets/images/Instagram_Glyph_Gradient_RGB.svg
    - assets/images/instagram_icon.png
    - assets/images/logo_white.png
    - assets/images/onboarding1_light.png
    - assets/images/onboarding1_dark.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/images/profile_default.png
    - assets/images/splash_branding.png
    - assets/images/splash_image.png
    - env

  fonts:
    - family: LINESeedJP
      fonts:
        - asset: assets/fonts/LINESeedJP/LINESeedJP_A_TTF_Bd.ttf
        - asset: assets/fonts/LINESeedJP/LINESeedJP_A_TTF_Eb.ttf
        - asset: assets/fonts/LINESeedJP/LINESeedJP_A_TTF_Rg.ttf
        - asset: assets/fonts/LINESeedJP/LINESeedJP_A_TTF_Th.ttf
